spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: 
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS public
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

server:
  port: 8080
  tomcat:
    max-part-count: 50

logging:
  level:
    com.broadridge.brx.matmapparser: INFO

brx:
  logical:
    model:
      filename: BRxLogicalModel.xlsx
      local:
        location: brxlogicalmodel/
      external:
        gitlab:
          url: https://git.devops.broadridge.net/GTO-FTB/EP/documentation
          location : sites/brx/data/
      ignored:
        sheets: Model Version,Alphabetical Lists,EnumerationSource Metadata,Business Models
      loading :
        strategy : gitlabRepository
  gitlab:
    access:
      token: ${GITLAB_ACCESS_TOKEN:dummy}
    host: https://git.devops.broadridge.net